# Generated by Django 3.2.7 on 2021-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(max_length=400),
        ),
    ]
