# Generated by Django 3.2.7 on 2021-10-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211002_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '10. Product Reviews'},
        ),
    ]
