# Generated by Django 3.2.7 on 2021-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
